---
- name: Populate service facts
  service_facts:

- name: Copy self-signed certs to expected location on nodes
  become: yes
  copy:
    src: "/tmp/domain.crt"
    dest: "/etc/pki/trust/anchors"
  register: _copy_ssc_result

# TODO convert to handler and remove skip_ansible_lint
- name: Update CA certificates on node
  command: >
    update-ca-certificates
  become: yes
  notify:
    - restart docker
  when:
    - "_copy_ssc_result.changed and 'docker.service' in ansible_facts.services"
  tags:
    - skip_ansible_lint

- name: Ensure registry server host DNS resolution is set in /etc/hosts
  become: yes
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK for registry server"
    block: |
      {{ registry_server_host_ip }} {{ local_registry_name }}