---

- name: Copy infra component - suse {{ component }} build script
  template:
    src: "{{ component }}-build.sh.j2"
    dest: "/tmp/build_component.sh"
    mode: "0755"

- name: Build and push infra component - suse {{ component }} image
  shell: |
    /tmp/build_component.sh
  args:
    chdir: "{{ devenv_root }}/openstack-helm-images"
