---
upstream_repos_clone_folder: "/opt"
suse_osh_registry_location: "{{ lookup('env','OPENSTACK_HELM_IMAGE_REGISTRY_LOCATION') | default('docker.io', true) }}"
suse_osh_image_version: "{{ lookup('env','OPENSTACK_HELM_IMAGE_VERSION') | default('pike', true) }}"
suse_libvirt_image_version: "{{ lookup('env','OPENSTACK_HELM_LIBVIRT_IMAGE_VERSION') | default('ubuntu-xenial-1.3.1-1ubuntu10.24', true) }}"
suse_ovs_image_version: "{{ lookup('env','OPENSTACK_HELM_OPENVSWITCH_IMAGE_VERSION') | default('v2.8.1', true) }}"

developer_mode: "{{ (lookup('env','SOCOK8S_DEVELOPER_MODE') | default('False', true) ) | bool }}"

socok8s_workspace: "{{ lookup('env','ANSIBLE_RUNNER_DIR') | default('~/suse-socok8s-deploy', true) }}"
socok8s_extravars: "{{ socok8s_workspace }}/env/extravars"
socok8s_ses_pools_details: "{{ socok8s_workspace }}/ses_config.yml"
socok8s_registry_cert: "{{ socok8s_workspace }}/certs/domain.crt"
socok8s_registry_certkey: "{{ socok8s_workspace }}/certs/domain.key"
socok8s_caasp_environment_details: "{{ socok8s_workspace }}/environment.json"
socok8s_libvirtuuid: "{{ socok8s_workspace }}/libvirt.uuid"

socok8s_deploy_config_location: "{{ socok8s_workspace }}"

ucp_namespace_name: "{{ ucp_namespace | default('ucp') }}"

suse_distro_identifier: opensuse
suse_airship_components_base_image: "opensuse/leap:15.0"

# check if argument is set in commandline for airship_local_images_flag value
# otherwise use corresponding environment variable to determine it
suse_airship_build_local_images: "{%- if airship_local_images_flag is defined -%}
                                    {{ airship_local_images_flag | bool }}
                                  {%- else -%}
                                    {{ lookup('env','AIRSHIP_BUILD_LOCAL_IMAGES') | default('False', true) | bool }}
                                  {%- endif -%}
                                 "

# Flag to be used when just want to use previously built local airship component images
# without need of re-building them.
suse_airship_use_local_images: "{{ lookup('env','AIRSHIP_USE_LOCAL_IMAGES') | default('False', true) | bool }}"

suse_airship_registry_location: "{%- if suse_airship_build_local_images or suse_airship_use_local_images -%}
                                   {{ ansible_hostname }}:5000
                                 {%- else -%}
                                   quay.io
                                 {%- endif -%}"

suse_airship_components_image_tag: "{%- if suse_airship_build_local_images or suse_airship_use_local_images -%}
                                      opensuse_15_latest
                                    {%- else -%}
                                      latest
                                    {%- endif -%}"
