---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-mariadb-soc
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openstack-mariadb-global
      component: mariadb
    actions:
      - method: merge
        path: .
      - method: delete
        path: .values.labels.prometheus_mysql_exporter
  storagePolicy: cleartext
data:
  wait:
    timeout: {{ openstack_helm_deploy_timeout }}
  test:
    enabled: {{ run_tests }}
    timeout: {{ test_timeout }}
  values:
    pod:
      resources:
        enabled: {{ openstack_helm_pod_resources_enabled['mariadb'] }}
    volume:
      size: {{ db_volume_size }}
      backup:
        size: {{ db_volume_size }}
...
