---
- name: "Prepare override file {{ _cmpnt_template }}"
  config_template:
    src: "{{ _cmpnt_template }}.j2"
    dest: "/tmp/socok8s-{{ _cmpnt_template }}"
    config_overrides: "{{ _cmpnt_overrides }}"
    config_type: yaml
  register: _usertemplatedata

# This needs specific executable, and therefore needs shell module,
# which causes an ansible-lint issue (no idempotency test). In the meantime
# that idempotency tests are created, we skip_ansible_lint
- name: Run the override file
  shell: "{{ _cmpnt_runcommand }}"
  args:
    executable: /bin/bash
    chdir: "{{ _cmpnt_chdir | default('/opt/openstack-helm') }}"
  environment:
    OSH_INFRA_PATH: /opt/openstack-helm-infra
  tags:
    - skip_ansible_lint
