kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: general
provisioner: kubernetes.io/rbd
parameters:
  monitors: 172.16.1.17:6789
  adminId: admin
  adminSecretName: pvc-ceph-conf-combined-storageclass
  adminSecretNamespace: ceph
  pool: rbd
  userId: admin
  userSecretName: pvc-ceph-client-key
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs
parameters:
  adminId: admin
  adminSecretName: pvc-ceph-cephfs-client-key
  adminSecretNamespace: ceph
  monitors: 172.16.1.17:6789
provisioner: ceph.com/cephfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
