---
- name: Include variables
  include_vars: "{{ item }}"
  loop:
    - "{{ playbook_dir }}/../vars/common-vars.yml"
    - "{{ playbook_dir }}/../vars/manifest.yml"
  tags:
    - always

- name: Install the necessary packages on the deployer node
  package:
    name: "{{ dev_patcher_packages }}"
    state: present
  register: install_packages
  until: install_packages  is success
  retries: 5
  delay: 2

- name: Clone upstream repositories for patching
  git:
    repo: "{{ item.value.src }}"
    dest: "{{ upstream_repos_clone_folder }}/{{ item.key }}"
    update: yes
    force: yes
    version: "{{ item.value.version }}"
  loop: "{{ (upstream_repos | default({})) | dict2items }}"
  register: _gitclone
  until: _gitclone is succeeded

- name: Get patch details
  include_tasks: patch-repos.yml
  loop: "{{ dev_patcher_patches | default([], True) }}"
  loop_control:
    loop_var: patchnumber

- name: Copy local code changes to cloned repos on deployer
  synchronize:
    src: "roles/dev-patcher/files/repos/"
    dest: "{{ upstream_repos_clone_folder }}/"