---
# ansible-lint: we need to reload the profiel and there is no ansible modules for that yet
- name: Reload apparmor profile
  command: "apparmor_parser -r /etc/apparmor.d/{{ item.item }}"
  when: item.changed
  loop: "{{ apparmor_copy.results | flatten(levels=1) }}"
  loop_control:
    label: "{{ item.item }}"
