---
- name: Load standard variables
  include_vars: "{{ item }}"
  loop:
    - "{{ playbook_dir }}/../vars/common-vars.yml"
    - "{{ playbook_dir }}/roles/common-ses/defaults/main.yml"
  tags:
    - always

- name: Create ses_cluster_configuration
  set_fact:
    ses_cluster_configuration: "{{ lookup('file', socok8s_ses_pools_details) | from_yaml }}"
  tags:
    - always

- name: Pre-flight checks for the role
  assert:
    that:
      - ceph_admin_keyring_b64key is defined
      - ceph_user_keyring_b64key is defined
  tags:
    - always

- name: Create a list of monitors
  include_role:
    name: common-ses
    tasks_from: list_of_mons

- name: Create Libvirt ceph cinder secret uuid
  shell: "uuidgen > {{ socok8s_libvirtuuid }}"
  args:
    creates: "{{ socok8s_libvirtuuid }}"
  delegate_to: localhost
  tags:
    - always

- name: Get libvirt secret
  set_fact:
    libvirt_ceph_cinder_secret_uuid: "{{ lookup('file', socok8s_libvirtuuid) }}"
  run_once: True
  tags:
    - always

- name: Create StorageClass for rook-based Ceph
  include_role:
    name: common-deployer
    tasks_from: apply_on_k8s
  loop:
    - action: create ceph storage class
      template_src_file: k8s-ses-storageclass-rook.yml.j2
      templated_location: /tmp/socok8s-ses-storage-class-rook.yml
  tags:
    - run
