---
- hosts: ses_nodes[0]
  vars:
    ses_config_file_path: "~/suse-osh-deploy/ses_config.yml"
  tasks:
    - name: Ensure the OSH config folder exists
      file:
        state: directory
        name: "{{ ses_config_file_path | dirname }}"
      delegate_to: localhost

    # The AIO ses creates /tmp/ses_config/ on localhost,
    # but that can disappear anytime. So we'll store
    # The ses config in our userspace.
    - name: Copy SES config in userspace
      copy:
        src: "/tmp/ses_config/ses_config.yml"
        dest: "{{ ses_config_file_path | dirname }}"
        remote_src: yes
      delegate_to: localhost

    # TODO(evrardjp): Add return code to latest call to make sure idempotency is known.
    # This step is needed until we decide to use ses_config created pools (and have properly tested them)
    - name: Create pools
      shell: "ceph -k /etc/ceph/ceph.client.admin.keyring osd pool ls | grep {{ item }} || ceph -k /etc/ceph/ceph.client.admin.keyring osd pool create {{ item }} 128 128"
      with_items:
        - rbd
        - volumes
        - cinder_backup
        - images
        - vms
