suse_osh_deploy_vip_with_cidr: 192.168.89.251
suse_airship_deploy_vip_with_cidr: 192.168.89.251
ceph_admin_keyring_b64key: QVFBWkUxdGNBQUFBQUJBQVJMdnF0eFQxbU9DZG0rNXM2SlhJM3c9PQ==
ceph_user_keyring_b64key: QVFBWkUxdGNBQUFBQUJBQVJMdnF0eFQxbU9DZG0rNXM2SlhJM3c9PQ==
suse_airship_deploy_site_name: demo
