---
- name: Include common vars
  include_vars: "{{ playbook_dir }}/../vars/common-vars.yml"

- name: Copy the certificates
  copy:
    src: "{{ socok8s_registry_cert }}"
    dest: "/etc/pki/trust/anchors"
  register: _copiedcert

- name: Refresh ca certs
  command: update-ca-certificates
  when: _copiedcert is changed

- name: Restart docker
  when: _copiedcert is changed
  service:
    name: docker
    state: restarted
