---
# Better to have another ansible role for running code against all worker nodes
- name: Subvolumes setup on control plane worker nodes
  import_tasks: subvolumes-setup.yml
  tags:
    - preinstall
