---
- name: Set CaaSP compute work node subvolume list
  set_fact:
    caasp_node_subvolumes:
      - "/var/lib/libvirt"
      - "/var/lib/nova"
      - "/var/lib/openstack-helm"
      - "/var/lib/neutron"
  when: ('airship-openstack-compute-workers' in group_names)

- name: Set CaaSP controller work node subvolume list
  set_fact:
    caasp_node_subvolumes:
      - "/var/lib/neutron"
  when: ('airship-openstack-compute-workers' not in group_names)

- name: Copy subvolume setup script
  template:
    src: caasp_worker_node_set_subvolumes.sh.j2
    dest: /tmp/caasp_worker_node_set_subvolumes.sh
    mode: "0755"
    force: yes

- name: Execute subvolume setup script
  shell: /tmp/caasp_worker_node_set_subvolumes.sh
  register: subvolume_cmd_out
  failed_when: subvolume_cmd_out.rc != 0

- name: Reboot node after successful subvolumes creation
  reboot: 
    msg: "Ansible triggered reboot after making subvolumes for Nova, Neutron and Libvirt"
    test_command: "kubectl get nodes"
  when: subvolume_cmd_out.stdout.find('reboot') >= 0
