---
- name: Load standard variables
  include_vars: "{{ playbook_dir }}/../common-vars.yml"

- name: Create ses_cluster_configuration
  set_fact:
    ses_cluster_configuration: "{{ lookup('file', suse_airship_deploy_ses_config_path) | from_yaml }}"

- name: Pre-fligt checks for the role
  assert:
    that:
      - ceph_admin_keyring_b64key is defined
      - ceph_user_keyring_b64key is defined
      - suse_airship_deploy_vip_with_cidr is defined

- name: Create a list of monitors (ip and port) if no override exists for it.
  set_fact:
    suse_airship_deploy_ceph_mons:  "[{% for ip in ses_cluster_configuration.ceph_conf.mon_host.split(',') %}'{{ ip }}:{{ ceph_mon_port | default(6789) }}'{% if not loop.last %},{% endif %}{% endfor %}]"
  when: suse_airship_deploy_ceph_mons is not defined
  tags:
    - always
    - run

#TODO JG move to ceph provisioner chart 
- name: Create ceph secrets yaml
  template:
    src: "suse-define-ses-secrets-in-k8s.yml.j2"
    dest: "/tmp/ceph-secrets.yaml"
    mode: "0600"

- name: Create ceph storage class yaml
  template:
    src: "suse-define-ses-storageclasses-in-k8s.yml.j2"
    dest: "/tmp/ceph-storage-classes.yaml"
    mode: "0600"

- name: "Apply ceph {{ item }} yaml"
  command: "kubectl apply -f /tmp/ceph-{{ item }}.yaml --overwrite=true"
  with_items:
    - secrets
    - storage-classes


# This is an arbitrary UUID value that's passed to the libvirt daemonset setup job for configuring a libvirt secret XML file
- name: Create Libvirt ceph cinder secret uuid
  shell: uuidgen
  register: libvirt_ceph_cinder_secret_uuid
