---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: glance-ccp
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: glance-global
      component: glance
    actions:
      - method: merge
        path: .
      - method: replace
        path: .values.pod
      - method: delete
        path: .values.ceph_client
  storagePolicy: cleartext
data:
  wait:
    timeout: 3000
  test:
    enabled: true
  values:
    bootstrap:
      enabled: false
    pod:
      replicas:
        api: 2
        registry: 2
    storage: rbd
    conf:
      ceph:
        enabled: true
        monitors: 172.16.1.17:6789
        admin_keyring: AQC1vztcAAAAABAARJjHnbF8TZnnTO/TWPDNtw==
      glance:
        glance_store:
          rbd_store_user: glance
          rbd_store_pool: images
...
