---

suse_airship_deploy_storage:
  adminId: admin
  adminSecretName: pvc-ceph-conf-combined-storageclass
  adminSecretNamespace: "{{ ceph_namespace_name }} "
  pool: rbd
  userId: admin
  userSecretName: pvc-ceph-client-key
  openstackUserSecretNamespace: "{{ openstack_namespace_name }}"
  ucpUserSecretNamespace: "{{ ucp_namespace_name }}"
  glance:
    user: admin
    pool: images
  cinder:
    user: admin
    pool: cinder
  cinder_backup:
    user: admin
    pool: backups
