---
- name: Reload apparmor profile
  command: "apparmor_parser -r /etc/apparmor.d/{{ item.item }}"
  when: item.changed
  loop: "{{ apparmor_copy.results | flatten(levels=1) }}"
  loop_control:
    label: "{{ item.item }}"
