---

- name: Install system packages for build images
  package:
    name: "{{ suse_build_images_packages }}"
    state: present
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags:
    - install

- name: Setup insecure docker registry for build images if such flag is set
  import_tasks: setup-build-registry.yml
  when:
    - suse_setup_insecure_build_registry | bool

- name: Build infra components
  include_tasks: build-infra-component.yml
  with_items: "{{ build_infra_components_list }}"
  loop_control:
    loop_var: component

- name: Build Openstack Services images via loci
  shell: |
    export LOCI_SRC_DIR={{ devenv_root }}/loci
    export REGISTRY_URI={{ local_registry_name }}:{{ local_registry_port }}/openstackhelm/
    export BASE_IMAGE=leap15
    export OPENSTACK_VERSION="{{ openstack_svcs_build_image_version }}"
    export PUSH_TO_REGISTRY=yes
    ./openstack/loci/build.sh
  args:
    chdir: "{{ devenv_root }}/openstack-helm-images"

- name: Remove insecure docker registry for build images if insecure flag is set
  import_tasks: clean-build-registry.yml
  when:
    - suse_setup_insecure_build_registry | bool

- name: Re-setup local secure registry if insecure registry was used for image build
  include_role:
    name: suse-osh-setup
    tasks_from: local-registry-setup
  when:
    - suse_setup_insecure_build_registry | bool

- name: Get list of recently built docker images on nodes
  shell: |
    docker images {{ local_registry_name }}:{{ local_registry_port }}/openstackhelm/*:{{suse_image_version}}-*-{{suse_image_distro}}* | awk 'NR>1 {print $1":"$2}'
  register: local_repo_images
  when:
    - suse_setup_insecure_build_registry | bool

- name: Publish local images to local secure registry server
  shell: |
    docker push {{ item }}
  with_items:
    - "{{ local_repo_images.stdout_lines }}"
  when:
    - local_repo_images is defined
    - local_repo_images.stdout_lines | length > 0
