---
# Example ses_config.yml file
# This file should be place in ~/suse-airship-deploy on the deployer node
ceph_conf:
  cluster_network: 192.168.89.0/24
  fsid: 06d75e51-4fe6-3b0e-a9ad-570c85bf9f98
  mon_host: 192.168.89.199
  mon_initial_members: linux-aojx
  public_network: 192.168.89.0/24
cinder:
  key: AQDDFltcBOOGEBAAMAK2WCIzzUfPS5DSfaDU/w==
  rbd_store_pool: volumes
  rbd_store_user: cinder
cinder-backup:
  key: AQDDFltcU0vuNRAAhege/zyKyo/Frk59U2gXTw==
  rbd_store_pool: cinder_backup
  rbd_store_user: cinder-backup
glance:
  key: AQDCFltc+tvDJxAAjrBJlHL7+3PZHrvV4knwkQ==
  rbd_store_pool: images
  rbd_store_user: glance
libvirt:
  key: AQDDFltcBOOGEBAAMAK2WCIzzUfPS5DSfaDU/w==
  rbd_store_pool: vms
  rbd_store_user: cinder
nova:
  rbd_store_pool: nova
radosgw_urls: []
