---
- name: Ensure folder for certs exists
  file:
    state: directory
    path: "{{ build_registry_certs_folder }}"

- name: Copy certs
  copy:
    src: "{{ item.0 }}"
    dest: "{{ item.1 }}"
  loop: "{{ localcerts | zip(oshdeployercerts) | list }}"
  vars:
    localcerts:
      - "{{ socok8s_registry_cert }}"
      - "{{ socok8s_registry_certkey }}"
    oshdeployercerts:
      - "{{ build_registry_certs_folder }}/{{ build_registry_cert_name }}"
      - "{{ build_registry_certs_folder }}/{{ build_registry_certkey_name }}"
