---
# tasks file for install-docker
- name: Include common vars
  include_vars: "{{ playbook_dir }}/../vars/{{ item }}"
  loop:
    - "common-vars.yml"
    - "developer-mode.yml"

- name: Install system packages for build images
  package:
    name: "{{ docker_packages }}"
    state: present
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags:
    - install

- name: Copy certs from userspace
  include_tasks: copy-certs.yml

- name: Ensure docker is started
  service:
    name: docker
    enabled: yes
    state: started

- name: Run your local secure registry
  vars:
    port: "{{ ('http://' + build_registry)| urlsplit('port') }}"
  docker_container:
    name: "{{ ('http://' + build_registry)| urlsplit('hostname') }}"
    image: "registry:2"
    ports:
      - "0.0.0.0:{{ port }}:{{ port }}"
    exposed_ports:
      - "{{ port }}"
    volumes:
      - "{{ build_registry_certs_folder }}:/certs"
    restart_policy: "always"
    env:
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/{{ build_registry_cert_name }}"
      REGISTRY_HTTP_TLS_KEY: "/certs/{{ build_registry_certkey_name }}"
