---

- hosts: osh-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - suse-dev-patcher

- hosts: osh-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - suse-build-images

- hosts: osh-deploy-cp
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - suse-osh-setup

- hosts: osh-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - suse-osh-deploy
