---

- name: Load standard variables
  include_vars: "{{ playbook_dir }}/../vars/common-vars.yml"

- name: Load existing extravars
  include_vars: "{{ socok8s_extravars }}"

# set socok8s_dcm_vip to same value as socok8s_ext_vip

# TODO: This should be improved in the future by creating a new VIP
# on a another network and then set socok8s_dcm_vip to new VIP
# value

- name: Set socok8s_dcm_vip in extravars
  lineinfile:
    path: "{{ socok8s_extravars }}"
    regexp: "^socok8s_dcm_vip.*"
    line: "socok8s_dcm_vip: {{ socok8s_ext_vip }}"
  tags:
    - install

- name: Set scale profile in extravars
  lineinfile:
    path: "{{ socok8s_extravars }}"
    regexp: "^scale_profile.*"
    line: "scale_profile: {{ extravars_scale_profile }}"
  tags:
    - install

- name: Set redeploy_osh_only in extravars
  lineinfile:
    path: "{{ socok8s_extravars }}"
    regexp: "^redeploy_osh_only.*"
    line: "redeploy_osh_only: {{ extravars_redeploy_osh_only }}"
  tags:
    - install
