---
- name: Include global vars
  include_vars: "{{ playbook_dir }}/../vars/common-vars.yml"

- name: Create pools in SES for socok8s usage
  become: yes
  include_role:
    name: ses
    tasks_from: openstack_config
  vars:
    ses_openstack_config: True
    ses_openstack_glance_pool:
      name: "{{ airship_ses_pools_prefix | default('') }}images"
      pg_num: "{{ ses_osd_pool_default_pg_num }}"
    ses_openstack_cinder_pool:
      name: "{{ airship_ses_pools_prefix | default('') }}volumes"
      pg_num: "{{ ses_osd_pool_default_pg_num }}"
    ses_openstack_nova_pool:
      name: "{{ airship_ses_pools_prefix | default('') }}vms"
      pg_num: "{{ ses_osd_pool_default_pg_num }}"
    ses_osh_rbd_pool:
      name: "{{ airship_ses_pools_prefix | default('') }}rbd"
      pg_num: "{{ ses_osd_pool_default_pg_num }}"
    ses_openstack_cinder_backup_pool:
      name: "{{ airship_ses_pools_prefix | default('') }}cinder_backup"
      pg_num: "{{ ses_osd_pool_default_pg_num }}"
    ses_openstack_pools:
      - "{{ ses_openstack_glance_pool }}"
      - "{{ ses_openstack_cinder_pool }}"
      - "{{ ses_openstack_nova_pool }}"
      - "{{ ses_openstack_cinder_backup_pool }}"
      - "{{ ses_osh_rbd_pool }}"

- name: Import SES configs to deployer
  import_tasks: ses_config.yml