---
# Example manifest for ingress cert.
# Shall be replaced with proper/valid set.
# Self-signed certs are not supported.
metadata:
  layeringDefinition:
    abstract: false
    layer: site
  name: ingress-crt
  schema: metadata/Document/v1
  labels:
    name: ingress-crt-site
  storagePolicy: cleartext
schema: deckhand/Certificate/v1
data: |
{{ ingress_cert_content | indent( width=2, indentfirst=True) }}
...
---
metadata:
  layeringDefinition:
    abstract: false
    layer: site
  name: ingress-ca
  schema: metadata/Document/v1
  labels:
    name: ingress-ca-site
  storagePolicy: cleartext
schema: deckhand/CertificateAuthority/v1
data: |
{{ ingress_ca_cert_content | indent( width=2, indentfirst=True) }}
...
---
metadata:
  layeringDefinition:
    abstract: false
    layer: site
  name: ingress-key
  schema: metadata/Document/v1
  labels:
    name: ingress-key-site
  storagePolicy: cleartext
schema: deckhand/CertificateKey/v1
data: |
{{ ingress_cert_key_content | indent( width=2, indentfirst=True) }}
...
