---
# Inspired by https://github.com/openstack/openstack-helm-infra/blob/master/roles/build-helm-packages/tasks/setup-helm-serve.yaml
- name: Copy systemd unit into place for helm server if it is not present
  template:
    src: helm-serve.service.j2
    dest: /etc/systemd/system/helm-serve.service
    mode: 0640

- name: Ensure helm serve service is running
  systemd:
    state: started
    daemon_reload: yes
    name: helm-serve
    enabled: yes

- name: Check if helm server is up
  wait_for:
    delay: 5
    host: 127.0.0.1
    port: 8879
    state: started

- name: Check port 8879 is running a helm repository
  uri:
    url: http://127.0.0.1:8879
    return_content: yes
  register: this
  failed_when: "'Helm Repository' not in this.content"

- name: Checking helm repos
  shell: |
    set -o pipefail
    helm repo list | grep 'http://localhost'
  register: _helmrepolist
  changed_when: false
  failed_when: false
  args:
    executable: /bin/bash

- name: Adding helm repos
  command: helm repo add localhost http://localhost:8879/charts
  when:
    - _helmrepolist.rc != 0
  args:
    executable: /bin/bash
