---
- name: Clone local-path provisioner
  become: yes
  git:
    repo: "https://github.com/rancher/local-path-provisioner"
    dest: "{{ upstream_repos_clone_folder }}/local-path-provisioner"
    update: yes
    force: yes
    version: "v0.0.10"
  register: _gitclone
  until: _gitclone is succeeded

- name: Install local-path storage provisioner
  command: "helm upgrade --install local-path-storage --namespace openstack {{ upstream_repos_clone_folder }}/local-path-provisioner/deploy/chart/"
  register: helm_result
  changed_when: helm_result.stdout is search('does not exist')

- name: Create new PodSecurityPolicy, ClusterRole and ClusterRoleBinding
  include_tasks: apply_on_k8s.yml
  loop:
    - action: create unprivileged PodSecurityPolicy allowing hostPath volume type
      template_src_file: k8s-unprivileged-pod-policy-and-binding.yml.j2
      templated_location: /tmp/socok8s-unprivileged-pod-policy-and-binding.yml
