---
- name: Ensure ses config directory exist
  file:
    path: "{{ ses_config_path }}"
    state: directory
  when:
    - ses_openstack_config

- name: Drop ceph conf and keys
  copy:
    dest: "{{ ses_config_path }}/{{ item.item }}"
    content: "{{ item.content | b64decode }}"
    mode: 0644
  with_items:
    - "{{ hostvars['ses'].ceph_files.results }}"
  when:
    - ses_openstack_config

- name: Get key values for ses-config.yml
  set_fact:
    "ceph_{{ item.name | regex_replace('[\\.\\-]', '_') }}_key":
       "{{lookup('ini', 'key section={{ item.name }} file={{ ses_config_path }}/ceph.{{ item.name }}.keyring') }}"
  with_items:
    - "{{ ses_openstack_keys }}"

- name: Generate ses-config.yml
  template:
    src: ses-config.yml.j2
    dest: "{{ ses_config_path }}/ses_config.yml"
  when:
    - ses_openstack_config
