---
- hosts: airship-openstack-compute-workers
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-configure-worker
      when: redeploy_osh_only is defined and redeploy_osh_only
      tags:
        - add_computenode 

- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - airship-deploy-osh
