---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Caasp is deployed and we have workers
      assert:
        that: "{{ groups['caasp-workers'] | length > 0 }}"
        fail_msg: You need Caasp deployed in order to deploy ses with rook
        success_msg: Caasp workers found
    - name: We have a deployer
      assert:
        that: "{{ groups['soc-deployer'] | length > 0 }}"
        fail_msg: You need a soc-deployer node in order to deploy ses with rook
        success_msg: Deployer found
- hosts: soc-deployer
  gather_facts: yes
  any_errors_fatal: true
  vars_files:
    - "{{ playbook_dir }}/../vars/common-vars.yml"
  tasks:
    - import_role:
        name: common-deployer
        tasks_from: kubectl-setup
    - import_role:
        name: ses-rook
