---
#
# (c) Copyright 2019 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

# This has to be idempotent.
# It will be called before the developer mode, so that developer mode can
# use the generated certs
# It will be called in CI after the deploy-osh/enroll caasp nodes, so that
# we can artifact the certs for reuse in the play to consume it.
- name: Generate certificates for docker registry
  hosts: localhost
  gather_facts: yes
  connection: local
  roles:
    - generate-certs
