---

- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-setup-deployer

- hosts: all
  gather_facts: false
  any_errors_fatal: true
  roles:
    - registry-server-setup

- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - dev-patcher

- hosts: airship-workers
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-configure-worker

- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: suse-build-images
      when: build_airship_images | default('False') | bool

- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-configure-caasp

- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-configure-ceph

- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-deploy-ucp
