---
- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-setup-deployer
      when: redeploy_osh_only is not defined or redeploy_osh_only != true

- hosts: all
  gather_facts: false
  any_errors_fatal: true
  roles:
    - registry-server-setup

- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: dev-patcher
      when: redeploy_osh_only is not defined or redeploy_osh_only != true
      become: yes

- hosts: airship-workers
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-configure-worker
      when: redeploy_osh_only is not defined or redeploy_osh_only != true

- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: suse-build-images
      when: build_airship_images | default('False') | bool

- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-configure-caasp
      when: redeploy_osh_only is not defined or redeploy_osh_only != true

- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-configure-ceph
      when: redeploy_osh_only is not defined or redeploy_osh_only != true

- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: airship-deploy-ucp
      when: redeploy_osh_only is not defined or redeploy_osh_only != true

- hosts: airship-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - airship-deploy-osh
