---
- name: Generate certificates for registry if none has been provided
  import_playbook: generic-generate_certs_for_local_registry.yml

- name: Prepare CaaSP workers for OpenStack and eventual dev registry
  hosts: caasp-workers
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: setup-caasp-workers
      tags:
        - workersetup
