---
- hosts: localhost
  gather_facts: no
  connection: local
  pre_tasks:
    - name: Load generic vars
      include_vars: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/../vars/common-vars.yml"
        - "{{ playbook_dir }}/../vars/deploy-on-openstack.yml"
  roles:
    - role: handle-nodes-on-openstack
      vars:
        servername_suffix: "ses"
        flavor: "{{ deploy_on_openstack_sesnode_flavor }}"
        image: "{{ deploy_on_openstack_sesnode_image }}"
        network: "{{ deploy_on_openstack_internal_network }}"
        securitygroups:
          - "{{ deploy_on_openstack_sesnode_securitygroup }}"
        groupname_for_inventory: "ses_nodes"
        delete: "{{ ((ses_node_delete | default('False')) | bool) }}"
