---
- name: Create privileged ClusterRoleBinding
  template:
    src: "privileged-cluster-role-binding.yml.j2"
    dest: "/tmp/privileged-cluster-role-binding.yml"
    mode: "0600"

- name: Apply privileged ClusterRoleBinding
  command: "kubectl apply -f /tmp/privileged-cluster-role-binding.yml --overwrite=true"
  register: create_privileged_cluster_role_binding_result
  changed_when: "create_privileged_cluster_role_binding_result.stdout|search('created')"
  tags:
    - skip_ansible_lint
